### ISSUE TITLE
Do you have the code to use imporved-DDPM??

### ISSUE THREAD

**Issue by Ultraman666** [mah533/Augmentation-of-ECG-Training-Dataset-with-CGAN#3]
I read your article "Synthetic ECG Signal Generation using Probabilistic Diffusion Models" on Google Scholar and was very interested in the method in which improved-DDPM is used to generate ECG signals. Could you please post the relevant code?

**Comment by mah533** [comment]
The Improved DDPM code we used was downloaded directly from their GitHub page (see their paper) and used as-is.
Hope it helps
